// Including all C++ headers
#include <limits>
#include <version>
#include <new>
#include <typeinfo>
#include <source_location>
#include <exception>
#include <initializer_list>
#include <compare>
#include <coroutine>
#include <concepts>
#include <stdexcept>
#include <system_error>
#include <utility>
#include <bitset>
#include <ratio>
#include <tuple>
#include <optional>
#include <variant>
#include <any>
#include <expected>
#include <type_traits>
#include <functional>
#include <memory>
#include <scoped_allocator>
#include <memory_resource>
#include <chrono>
#include <typeindex>
#include <execution>
#include <charconv>
#include <stacktrace>
#include <string>
#include <string_view>
#include <locale>
#include <codecvt>
#include <array>
#include <deque>
#include <forward_list>
#include <list>
#include <queue>
#include <stack>
#include <vector>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <span>
#include <iterator>
#include <ranges>
#include <algorithm>
#include <complex>
#include <bit>
#include <random>
#include <valarray>
#include <numeric>
#include <numbers>
#include <iosfwd>
#include <iostream>
#include <ios>
#include <streambuf>
#include <istream>
#include <ostream>
#include <iomanip>
#include <sstream>
#include <strstream>
#include <fstream>
#include <filesystem>
#include <syncstream>
#include <spanstream>
#include <regex>
#include <atomic>
#include <stdatomic.h>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfenv>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
// Include end
#include <template/arysystem.hpp>
#include <template/combinations.hpp>
#include <template/debugprint.hpp>
#include <template/edit_distance.hpp>
#include <template/enum_divisors.hpp>
#include <template/gcd_lcm.hpp>
#include <template/ioutility.hpp>
#include <template/inverse_element.hpp>
#include <template/ispalindrome.hpp>
#include <template/isprime.hpp>
#include <template/powmod.hpp>
#include <template/prime_factorize.hpp>
#include <template/rud.hpp>
#include <template/sha256.hpp>
#include <template/unique_erase.hpp>
#include <atcoder/all>